spring:
  application:
    name: jidlobot
logging:
  level:
    root: INFO
    eu.kratochvil: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints (restrict in production)
  endpoint:
    health:
      show-details: "always"  # Show detailed health information

server:
  shutdown: graceful


slack:
  bot-token: ${SLACK_BOT_TOKEN}
  app-token: ${SLACK_APP_LEVEL_TOKEN}

menu:
  url: "https://www.jidlovice.cz/telehouse/"
  cache-enabled: true
  cache-for-seconds: 3600
