spring:
  application:
    name: jidlobot
logging:
  level:
    root: INFO
    eu.kratochvil: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
      access: unrestricted
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

server:
  shutdown: graceful

application:
  time-zone: Europe/Prague

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  app-token: ${SLACK_APP_LEVEL_TOKEN}

menu:
  url: "https://www.jidlovice.cz/api/v1/branch/3/menu/{date}?include_internal_tags=false"
  cache-enabled: true
  cache-for-seconds: 3600
