apiVersion: apps/v1
kind: Deployment
metadata:
  name: jidlobot-deployment
  namespace: fun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jidlobot
  template:
    metadata:
      labels:
        app: jidlobot
    spec:
      containers:
        - name: jidlobot
          image: ghcr.io/kratochj/jidlobot:v2.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-alt
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-secrets
                  key: SLACK_BOT_TOKEN
            - name: SLACK_APP_LEVEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-secrets
                  key: SLACK_APP_LEVEL_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: jidlobot-service
  namespace: fun
spec:
  selector:
    app: jidlobot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-alt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jidlobot
  namespace: fun
spec:
  rules:
    - host: jidlobot.kstage.dialog.internal
      http:
        paths:
          - backend:
              service:
                name: jidlobot-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: jidlobot-podscrape
  namespace: fun
spec:
  selector:
    matchLabels:
      app: jidlobot
  namespaceSelector:
    matchNames:
      - fun
  podMetricsEndpoints:
    - port: http-alt
      path: /actuator/prometheus
      interval: 15s
